### PR TITLE
Add bootloader logos for m1n1

### PR DESCRIPTION
**Pull request by davide125**
Add logos required by m1n1, a bootloader for Apple Silicon systems. This
is the CentOS equivalent of https://pagure.io/fedora-logos/pull-request/21 and will allow building
m1n1 and asahi-installer in EPEL 10 (https://bugzilla.redhat.com/show_bug.cgi?id=2315498
https://bugzilla.redhat.com/show_bug.cgi?id=2315499), which are needed by the CentOS Hyperscale SIG to work on Apple Silicon enablement for CentOS Stream 10.

### CODE REVIEW

**Comment by davide125** [comment]
Filed https://issues.redhat.com/browse/RHEL-60809 for the centos-logos package in CentOS Stream 10.

**Comment by areguera** [comment]
Images look good to me. @carlwgeorge do you have any consideration for packaging?

**Comment by carlwgeorge** [comment]
I don't see anything in the [current C10 spec file](https://gitlab.com/redhat/centos-stream/rpms/centos-logos/-/blob/c10s/centos-logos.spec) that will install these files, so after we merge this and tag a new version the spec file will need to be adjusted not just for the new version but also to install those files.  I don't know off hand where in the system they should be installed, so ideally @davide125 can send an MR for those changes too.

**Comment by davide125** [comment]
@carlwgeorge put up https://gitlab.com/redhat/centos-stream/rpms/centos-logos/-/merge_requests/8 to update the package.

**Pull request merged**
